repos:
  # ------------------------
  # Lua formatting
  # ------------------------
  - repo: local
    hooks:
      - id: stylua
        name: Stylua Lua formatter
        entry: stylua
        language: system
        types: [lua]
        files: "\\.lua$"
        args: ["--config-path", ".stylua.toml"]  # optional if you have a config

  # ------------------------
  # YAML & Markdown formatting
  # ------------------------
  - repo: local
    hooks:
      - id: biome
        name: Biome code formatter
        entry: biome format
        language: system
        types: [yaml, markdown]
        files: "\\.(yaml|yml|md)$"
