repos:
  # ------------------------
  # Lua formatting & linting
  # ------------------------
  - repo: https://github.com/JohnnyMorganz/stylua
    rev: v2.3.0  # Use latest stable version
    hooks:
      - id: stylua
        files: \.lua$
        args: ["--config-path", ".stylua.toml"]  # Optional: if you have a stylua config

  - repo: https://github.com/biomejs/pre-commit
    rev: v2.2.5 # Use the sha / tag you want to point at
    hooks:
      - id: biome-check
        name: Biome code formatter
        types: [yaml, markdown]
        files: "\\.(yaml|yml|md)$"
